version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: root
  MYSQL_DATABASE: most
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/schema.sql

  server:
    build: .
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    command: npm start

  client:
    build: .
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3003:3003
    command: npm start